### ISSUE TITLE
Rename dangerous constants

### ISSUE THREAD

**Issue by szepeviktor** [shipmonk-rnd/dead-code-detector#130]
Please consider renaming these constants.

https://github.com/shipmonk-rnd/dead-code-detector/blob/c9602b505b605e3a18bc4a7cdad3330c67aaf847/src/Enum/ClassLikeKind.php#L8-L11

This highly popular package uses an underscore: https://github.com/nikic/PHP-Parser/tree/master/lib/PhpParser/Node/Stmt

**Comment by janedbal** [comment]
What is the problem with current naming?

**Comment by szepeviktor** [comment]
The third one couldn't be named "CLASS" to it had got another "S".
The other three are PHP keywords. Technically you may name it "TRAIT" but using keywords for user defined names is dangerous, see "CLASS".

**Comment by janedbal** [comment]
I believe `nikic/php-parser` also sticks with just technical limitations (as we are). Those suffixed with underscore are just invalid names for classes. Probably the only exception there is [Enum_](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Stmt/Enum_.php), but that one is [soft reserved](https://www.php.net/manual/en/reserved.other-reserved-words.php).

**Comment by szepeviktor** [comment]
Okay, I just bravely run away.
I am not (yet) a businessman taking risks.

**Comment by janedbal** [comment]
Btw nikic also uses constants named as PHP keywords: https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Modifiers.php#L10
