### ISSUE TITLE
Detect `Doctrine\ORM\EntityRepository` as entry point

### ISSUE THREAD

**Issue by ruudk** [shipmonk-rnd/dead-code-detector#87]
It should not complain about the constructor.

**Comment by janedbal** [comment]
So, you are using `$em->getRespository()` approach? In such case, I'd expect no need for constructor declaration in children. In past (before we got rid of `EntityRepository` completely), we had all repositories registered as DIC services (which should be detected by dead-code-detector).

But I'm just curious, I'll add support for this, thanks.

**Comment by ruudk** [comment]
No, we're not using the `$em->getRepository()` approach but inject repositories as dependencies. But it's related to this: https://github.com/shipmonk-rnd/dead-code-detector/issues/92
